### ISSUE TITLE
We need code and problems about I/O form terminal

### ISSUE THREAD

**Issue by xaca** [xaca/java_fundamentals#12]
What is the best way to ask for data form terminal? We need some recomendations, and diferent problems about printing.

**Comment by cryguy** [comment]
ask for input from console/terminal? do you mean stdin or input after running?

**Comment by xaca** [comment]
@cryguy yes standar input/output, running in the console

**Comment by yashdeeph709** [comment]
Can I Add code for BufferedReader and Scanner Console IO?

**Comment by xaca** [comment]
@yashdeeph709 Course we are looking for differents examples
