### ISSUE TITLE
We need help with README file to translate to spanish and other languages.

### ISSUE THREAD

**Issue by xaca** [xaca/java_fundamentals#56]
We like to complement REAME file, with more instructions and in different languges, like portuguese, german...

**Comment by ghost** [comment]
Hey :)
I would like to help with the german translation of the current README file.

**Comment by vlasebian** [comment]
What other languages do you need to translate in?

**Comment by xaca** [comment]
@SNException Cool!

**Comment by xaca** [comment]
@vlasebian Many different languages...

**Comment by luizcavalcanti** [comment]
Can help with brazilian portuguese. What's the best way to proceed?

**Comment by xaca** [comment]
@luizcavalcanti Could you start with readme file, also we need portuguese help in [https://github.com/xaca/holamundo.co/issues/3](url)
